---
title: Brent Potter
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
email: 
description: 
baseurl: 
url: http://brentpotter.github.io
twitter_username: 
github_username: 
markdown: kramdown
