---
title: Brent Potter
timezone: UTC
collections:
  portfolio:
    title: Portfolio
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: brent.ltd@gmail.com
description: |
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: 
url: http://brentpotter.github.io
twitter_username: 
github_username: 
markdown: kramdown
